apiVersion: v1
kind: Namespace
metadata:
  labels:
    argocd.argoproj.io/instance: all-namespaces
    kubernetes.io/metadata.name: argocd
  name: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: external-secrets
  name: external-secrets
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: cert-manager
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: istio-ingress
  name: istio-ingress
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: istio-system
  name: istio-system
