apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    labels:
        env: uat
    name: customer-emchwmlo-myapp235-uat22-management
    namespace: argocd
spec:
    destination:
        server: https://kubernetes.default.svc
    project: default
    source:
        path: deploy/clusters/uat22-management/customers/customer-emchwmlo/components/my-app
        repoURL: https://github.com/holos-run/multi-sources-example.git
        targetRevision: main
