apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    labels:
        env: prod
    name: customer-emchwmlo-myapp193-prod6-internal
    namespace: argocd
spec:
    destination:
        server: https://kubernetes.default.svc
    project: default
    source:
        path: deploy/clusters/prod6-internal/customers/customer-emchwmlo/components/my-app
        repoURL: https://github.com/holos-run/multi-sources-example.git
        targetRevision: main
