apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    argocd.argoproj.io/instance: argocd-argocd-secrets
  name: argocd-redis
  namespace: argocd
spec:
  dataFrom:
  - rewrite:
    - transform:
        template: password
    sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: argocd-redis
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      data:
        auth: '{{ .password }}'
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  labels:
    argocd.argoproj.io/instance: argocd-argocd-secrets
  name: argocd-redis
  namespace: argocd
spec:
  allowRepeat: true
  digits: 4
  length: 16
  noUpper: false
  symbols: 0
