apiVersion: v1
kind: Service
metadata:
  labels:
    argocd.argoproj.io/instance: staging-ap-my-chart
  name: simple-service
  namespace: staging-ap
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: trivial-go-web-app
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    argocd.argoproj.io/instance: staging-ap-my-chart
  name: simple-deployment
  namespace: staging-ap
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trivial-go-web-app
  template:
    metadata:
      labels:
        app: trivial-go-web-app
    spec:
      containers:
      - env:
        - name: ENV
          value: dev
        - name: ENV_TYPE
          value: non-prod
        - name: REGION
          value: dev
        - name: PAYPAL_URL
          value: staging2.paypal.com
        - name: DB_USER
          value: non-prod-user
        - name: DB_PASSWORD
          value: non-prod-password
        - name: GPU_ENABLED
          value: "0"
        - name: UI_THEME
          value: light
        - name: CACHE_SIZE
          value: 1024kb
        - name: PAGE_LIMIT
          value: "50"
        - name: SORTING
          value: Ascending
        - name: N_BUCKETS
          value: "42"
        image: docker.io/kostiscodefresh/simple-env-app:2.0
        imagePullPolicy: Always
        name: webserver-simple
        ports:
        - containerPort: 8080
