apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    labels:
        env: all
    name: all-namespaces
    namespace: argocd
spec:
    destination:
        server: https://kubernetes.default.svc
    project: default
    source:
        path: deploy/components/namespaces
        repoURL: https://github.com/holos-run/multi-sources-example.git
        targetRevision: main
