apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    labels:
        env: staging-us
    name: staging-us-my-chart
    namespace: argocd
spec:
    destination:
        namespace: staging-us
        server: https://kubernetes.default.svc
    project: default
    source:
        path: deploy/environments/staging-us/components/my-chart
        repoURL: https://github.com/holos-run/multi-sources-example
        targetRevision: main
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
