apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    argocd.argoproj.io/instance: network-istio-gateway
    gateway.istio.io/managed: istio.io-gateway-controller
    gateway.networking.k8s.io/gateway-name: default
    istio.io/gateway-name: default
  name: default-istio
  namespace: istio-ingress
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    argocd.argoproj.io/instance: network-istio-gateway
  name: gateway-cert
  namespace: istio-ingress
spec:
  commonName: holos.localhost
  dnsNames:
  - holos.localhost
  - '*.holos.localhost'
  issuerRef:
    kind: ClusterIssuer
    name: local-ca
  secretName: gateway-cert
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  labels:
    argocd.argoproj.io/instance: network-istio-gateway
  name: default
  namespace: istio-ingress
spec:
  gatewayClassName: istio
  listeners:
  - allowedRoutes:
      namespaces:
        from: Same
    name: http
    port: 80
    protocol: HTTP
  - allowedRoutes:
      namespaces:
        from: Same
    name: https
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - kind: Secret
        name: gateway-cert
      mode: Terminate
