apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  labels:
    argocd.argoproj.io/instance: security-local-ca
  name: local-ca
  namespace: cert-manager
spec:
  ca:
    secretName: local-ca
