apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    argocd.argoproj.io/instance: customer-emchwmlo-myapp364-prod8-customer
  name: simple-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: trivial-go-web-app
  template:
    metadata:
      labels:
        app: trivial-go-web-app
    spec:
      containers:
      - env:
        - name: CUSTOMER_ID
          value: customer-emchwmlo
        - name: ENABLED
          value: "false"
        - name: IMAGE
          value: oci://example.com/espfwpgu
        - name: VERSION
          value: v78.74.0
        - name: DOMAIN
          value: pvyvpnnqcp.example
        - name: REPLICAS
          value: "4"
        - name: CLIENT_ID
          value: https://wylpmodgfa.example
        - name: ISSUER
          value: https://feqkgcszkn.example
        - name: PROJECT_ID
          value: my-project-400823
        - name: ACCOUNT_ID
          value: "7.11523864782e+11"
        - name: ARN
          value: arn:partition:service:region:account-id:awbmwkhj
        - name: CORES
          value: "37.3"
        - name: MEMORY
          value: "13252"
        image: docker.io/kostiscodefresh/simple-env-app:0.1.0
        imagePullPolicy: Always
        name: webserver-simple
        ports:
        - containerPort: 8080
